services:
  maria:
    image: 'mariadb:latest'
    environment:
      - 'MYSQL_DATABASE=TMDB'
      - 'MYSQL_PASSWORD=12345678'
      - 'MYSQL_ROOT_PASSWORD=12345678'
      - 'MYSQL_USER=ROOT'
    ports:
      - '3306:3306'
networks:
  TMDB:
    driver: bridge